[package]
name = "ipfs-http"
version = "0.1.0"
authors = ["Joonas Koivunen <joonas@equilibrium.co>"]
edition = "2018"
build = "build.rs"

[build-dependencies]
vergen = "3.1.0"
prost-build = "0.6.1"

[dependencies]
cid = "0.4.0"
env_logger = "0.7.1"
futures = "0.3.4"
ipfs = { path = ".." }
log = "0.4.8"
multibase = "0.8.0"
multihash = "0.10.1"
# openssl is required for rsa keygen but not used by the rust-ipfs or it's dependencies
openssl = "0.10.28"
prost = "0.6.1"
serde = { version = "1.0.105", features = ["derive"] }
serde_json = "1.0.48"
structopt = "0.3.12"
thiserror = "1.0.13"
tokio = { version = "0.2.13", features = ["full"] }
warp = "0.2.2"
bytes = "0.5.4"
